FROM python:3.12-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi

COPY . .
RUN touch news_archive.txt && chmod 666 news_archive.txt

CMD ["poetry", "run", "fastapi", "run", "app/main.py"]
